mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.zy.flimticketserver.entity

spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flimtiket?serverTimezone=GMT%2B8
    username: root
    password: zy131456
    dpcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
